version: "3.0"
services:

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
      discovery.type: single-node

    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:8.6.2
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m

    ports:
      - 5044:5044

    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ../traffic_logs.json:/usr/share/traffic_logs.json
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - elk
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  elk:
    driver: bridge
    